import {
  FileChange,
  ReviewResult,
  ProviderError,
  ActionInputs,
  GitHubReview,
  GitHubReviewComment,
} from '../types';
import { FileUtils } from '../utils';

/**
 * Service for building various types of comments for GitHub PRs
 */
export class CommentBuilder {
  constructor(private config: ActionInputs) {}

  /**
   * Format a review comment with proper structure
   */
  formatReviewComment(comment: string, filename: string, chunk?: any): string {
    let formatted = `📄 **${filename}**`;

    if (chunk && chunk.index && chunk.total > 1) {
      formatted += ` *(Part ${chunk.index}/${chunk.total} - Lines ${chunk.startLine}-${chunk.endLine})*`;
    }

    formatted += `\n\n`;

    // Clean up the comment and add proper formatting
    const cleanComment = comment.trim();

    // Add some structure to the comment if it doesn't have any
    if (
      !cleanComment.includes('##') &&
      !cleanComment.includes('**') &&
      !cleanComment.includes('-')
    ) {
      // Split into sentences and format as bullet points if multiple issues
      const sentences = cleanComment.split(/[.!?]+/).filter(s => s.trim().length > 0);
      if (sentences.length > 1) {
        formatted += sentences.map(sentence => `• ${sentence.trim()}`).join('\n') + '\n';
      } else {
        formatted += `💡 ${cleanComment}\n`;
      }
    } else {
      formatted += cleanComment;
    }

    return formatted;
  }

  /**
   * Build the final comprehensive review comment
   */
  buildFinalComment(results: ReviewResult[], files: FileChange[]): string {
    const summary = FileUtils.getChangesSummary(files);
    const totals = FileUtils.getTotalChanges(files);
    const provider = results[0]?.provider || this.config.provider;
    const reviewedFilesCount = new Set(results.map(r => r.comment.match(/### 📄 (.+)/)?.[1])).size;

    let comment = `## 🤖 AI Code Review Report\n\n`;

    // Add summary section
    comment += this.buildSummarySection(provider, files, reviewedFilesCount, totals, results);

    // Add files overview
    comment += this.buildFilesOverviewSection(files, results);

    // Add review rules if any
    comment += this.buildReviewRulesSection();

    comment += `---\n\n`;

    // Add main content
    if (results.length === 0) {
      comment += this.buildNoIssuesSection(files);
    } else {
      comment += this.buildDetailedReviewSection(results);
    }

    // Add technical details
    comment += this.buildTechnicalDetailsSection(results, summary, provider);

    // Add footer
    comment += this.buildFooter();

    return comment;
  }

  /**
   * Build error comment for provider errors
   */
  buildErrorComment(error: ProviderError, filename?: string): string {
    const timestamp = new Date().toISOString();

    let comment = `## ❌ AI Code Review Error\n\n`;

    // Add error metadata
    comment += `**Provider:** ${error.provider.toUpperCase()}\n`;
    comment += `**Time:** ${timestamp}\n`;
    comment += `**Status Code:** ${error.statusCode || 'N/A'}\n`;
    if (filename) {
      comment += `**File:** ${filename}\n`;
    }
    comment += `\n`;

    // Add error details
    comment += `### 🚨 Error Details\n\n`;
    comment += `\`\`\`\n${error.message}\n\`\`\`\n\n`;

    // Add suggested actions based on error type
    comment += this.buildErrorSuggestionsSection(error);

    // Add next steps
    comment += `### 🔧 Next Steps\n\n`;
    comment += `- The code review action will be marked as failed\n`;
    comment += `- You can re-run the action after addressing the issue\n`;
    comment += `- Consider checking the GitHub Actions logs for more details\n\n`;

    comment += `---\n`;
    comment += `<sub>🤖 Generated by [AI Code Review Action](https://github.com/legiaquan/code-review-action) • Error ID: \`${Date.now()}\`</sub>`;

    return comment;
  }

  /**
   * Build a GitHub review with suggestions for individual changes
   */
  buildReviewWithSuggestions(results: ReviewResult[], files: FileChange[]): GitHubReview {
    const totals = FileUtils.getTotalChanges(files);
    const provider = results[0]?.provider || this.config.provider;
    const reviewedFilesCount = new Set(results.map(r => r.comment.match(/### 📄 (.+)/)?.[1])).size;

    // Build the main review body
    const body = this.buildReviewBody(provider, files, reviewedFilesCount, totals, results);

    // Build individual review comments with suggestions
    const comments: GitHubReviewComment[] = [];

    results.forEach(result => {
      // Extract suggestions from the result if available
      if (result.suggestions && result.suggestions.length > 0) {
        result.suggestions.forEach(suggestion => {
          comments.push({
            path: suggestion.path,
            line: suggestion.line,
            side: suggestion.side,
            startLine: suggestion.startLine,
            endLine: suggestion.endLine,
            startSide: suggestion.startSide,
            endSide: suggestion.endSide,
            body: suggestion.body,
            position: suggestion.line, // Use line number as position for now
          });
        });
      } else {
        // If no specific suggestions, create a general comment
        const filename = this.extractFilenameFromComment(result.comment);
        if (filename) {
          comments.push({
            path: filename,
            line: 1, // Default to first line if we can't determine specific line
            side: 'RIGHT',
            body: this.formatSuggestionComment(result.comment),
            position: 1,
          });
        }
      }
    });

    // Determine review event based on results
    const event: 'COMMENT' | 'REQUEST_CHANGES' | 'APPROVE' =
      results.length === 0 ? 'APPROVE' : 'COMMENT';

    return {
      body,
      event,
      comments,
    };
  }

  /**
   * Build the main review body (summary)
   */
  private buildReviewBody(
    provider: string,
    files: FileChange[],
    reviewedFilesCount: number,
    totals: any,
    results: ReviewResult[],
  ): string {
    let body = `## 🤖 AI Code Review Report\n\n`;

    // Add summary section
    body += this.buildSummarySection(provider, files, reviewedFilesCount, totals, results);

    // Add files overview
    body += this.buildFilesOverviewSection(files, results);

    // Add review rules if any
    body += this.buildReviewRulesSection();

    body += `---\n\n`;

    // Add main content
    if (results.length === 0) {
      body += this.buildNoIssuesSection(files);
    } else {
      body += this.buildDetailedReviewSection(results);
    }

    // Add technical details
    body += this.buildTechnicalDetailsSection(
      results,
      FileUtils.getChangesSummary(files),
      provider,
    );

    // Add footer
    body += this.buildFooter();

    return body;
  }

  /**
   * Format a comment for suggestion display
   */
  private formatSuggestionComment(comment: string): string {
    // Clean up the comment and remove file headers
    let cleanComment = comment.replace(/^📄 \*\*[^*]+\*\*.*?\n\n/, '');

    // Remove chunk information if present
    cleanComment = cleanComment.replace(/\*\(Part \d+\/\d+ - Lines \d+-\d+\)\*\n\n/, '');

    return cleanComment.trim();
  }

  /**
   * Extract filename from comment text
   */
  private extractFilenameFromComment(comment: string): string | null {
    const match = comment.match(/📄 \*\*([^*]+)\*\*/);
    return match ? match[1] : null;
  }

  /**
   * Build summary section of the review comment
   */
  private buildSummarySection(
    provider: string,
    files: FileChange[],
    reviewedFilesCount: number,
    totals: any,
    results: ReviewResult[],
  ): string {
    let section = `### 📊 Review Summary\n`;
    section += `| Metric | Value |\n`;
    section += `|--------|-------|\n`;
    section += `| **🤖 AI Provider** | ${provider.toUpperCase()} |\n`;
    section += `| **📁 Files Changed** | ${files.length} |\n`;
    section += `| **🔍 Files Reviewed** | ${reviewedFilesCount} |\n`;
    section += `| **📈 Total Changes** | +${totals.additions} -${totals.deletions} (~${totals.changes} lines) |\n`;
    section += `| **🎯 Issues Found** | ${results.length} |\n\n`;
    return section;
  }

  /**
   * Build files overview section
   */
  private buildFilesOverviewSection(files: FileChange[], results: ReviewResult[]): string {
    let section = `### 📋 Files Overview\n`;
    files.forEach(file => {
      const statusEmoji = this.getStatusEmoji(file.status);
      const hasReview = results.some(r => r.comment.includes(file.filename));
      const reviewStatus = hasReview ? '🔍 Reviewed' : '✅ Clean';
      section += `- ${statusEmoji} \`${file.filename}\` (+${file.additions} -${file.deletions}) - ${reviewStatus}\n`;
    });
    section += `\n`;
    return section;
  }

  /**
   * Build review rules section
   */
  private buildReviewRulesSection(): string {
    if (this.config.rules.length === 0) {
      return '';
    }

    let section = `### 📝 Review Rules Applied\n`;
    this.config.rules.forEach((rule, index) => {
      section += `${index + 1}. ${rule}\n`;
    });
    section += `\n`;
    return section;
  }

  /**
   * Build no issues found section
   */
  private buildNoIssuesSection(files: FileChange[]): string {
    let section = `## ✅ Excellent Work!\n\n`;
    section += `🎉 **No issues found!** Your code looks clean and follows best practices.\n\n`;
    section += `All ${files.length} changed file(s) have been reviewed and everything looks good to go! 🚀\n\n`;
    return section;
  }

  /**
   * Build detailed review comments section
   */
  private buildDetailedReviewSection(results: ReviewResult[]): string {
    let section = `## 🔍 Detailed Review Comments\n\n`;
    results.forEach((result, index) => {
      section += `### ${index + 1}. ${result.comment}\n\n`;
      if (index < results.length - 1) {
        section += `---\n\n`;
      }
    });
    return section;
  }

  /**
   * Build technical details section
   */
  private buildTechnicalDetailsSection(
    results: ReviewResult[],
    summary: any,
    provider: string,
  ): string {
    const totalTokens = results.reduce((sum, r) => sum + (r.tokensUsed || 0), 0);
    const totalCost = results.reduce((sum, r) => sum + (r.costUSD || 0), 0);

    let section = `\n<details>\n<summary>🔢 Technical Details</summary>\n\n`;

    // File status breakdown
    section += `**File Status Breakdown:**\n`;
    Object.entries(summary).forEach(([status, count]) => {
      const emoji = this.getStatusEmoji(status);
      section += `- ${emoji} ${status}: ${count} file(s)\n`;
    });

    // AI usage stats
    if (totalTokens > 0 || totalCost > 0) {
      section += `\n**AI Usage:**\n`;
      if (totalTokens > 0) {
        section += `- Tokens consumed: ${totalTokens.toLocaleString()}\n`;
      }
      if (totalCost > 0) {
        section += `- Estimated cost: $${totalCost.toFixed(4)}\n`;
      }
    }

    // Review configuration
    section += `\n**Review Configuration:**\n`;
    section += `- Provider: ${provider}\n`;
    section += `- Review Level: ${this.config.reviewLevel}\n`;
    section += `- Max Chunk Lines: ${this.config.maxChunkLines}\n`;
    section += `- Custom Rules: ${this.config.rules.length > 0 ? 'Yes' : 'No'}\n`;

    section += `\n</details>\n\n`;
    return section;
  }

  /**
   * Build error suggestions section based on error type
   */
  private buildErrorSuggestionsSection(error: ProviderError): string {
    let section = `### 💡 Suggested Actions\n\n`;

    if (error.message.includes('quota') || error.message.includes('rate limit')) {
      section += `This appears to be a quota or rate limit error. Here are some options:\n\n`;
      section += `1. **Wait and retry** - The error message may include a retry delay\n`;
      section += `2. **Check your API plan** - You may need to upgrade your ${error.provider} API plan\n`;
      section += `3. **Use a different provider** - Consider switching to OpenAI or another provider\n`;
      section += `4. **Review usage patterns** - Check if you're making too many requests\n\n`;

      if (error.provider === 'gemini') {
        section += `For Gemini specifically:\n`;
        section += `- Free tier has daily and per-minute limits\n`;
        section += `- Consider upgrading to a paid plan for higher quotas\n`;
        section += `- See [Gemini API Rate Limits](https://ai.google.dev/gemini-api/docs/rate-limits) for details\n\n`;
      }
    } else if (error.message.includes('authentication') || error.message.includes('API key')) {
      section += `This appears to be an authentication error:\n\n`;
      section += `1. **Verify API key** - Check that your ${error.provider.toUpperCase()}_API_KEY secret is correctly set\n`;
      section += `2. **Check key permissions** - Ensure the API key has the necessary permissions\n`;
      section += `3. **Key expiration** - Some API keys may have expiration dates\n\n`;
    } else {
      section += `1. **Check the error message** above for specific details\n`;
      section += `2. **Verify your ${error.provider} API configuration**\n`;
      section += `3. **Try again** - This might be a temporary issue\n`;
      section += `4. **Contact support** if the problem persists\n\n`;
    }

    return section;
  }

  /**
   * Build footer section
   */
  private buildFooter(): string {
    return `---\n<sub>🤖 Generated by [AI Code Review Action](https://github.com/legiaquan/code-review-action) • Review ID: \`${Date.now()}\`</sub>`;
  }

  /**
   * Get emoji for file status
   */
  private getStatusEmoji(status: string): string {
    switch (status) {
      case 'added':
        return '🆕';
      case 'modified':
        return '📝';
      case 'removed':
        return '🗑️';
      case 'renamed':
        return '📋';
      default:
        return '📄';
    }
  }
}
